chore: final update

diff --git a/scripts/commit-msg b/scripts/commit-msg
--- a/scripts/commit-msg
+++ b/scripts/commit-msg
@@ -1,9 +1,12 @@
 #!/bin/sh
 
 # Call script with commit msg as first argument
+.git/hooks/scripts/commit-msg-hook "$1"
+value=$?
+
 if ! .git/hooks/scripts/commit-msg-hook "$1"; then
-  echo "Commit message does not have the required format."
+  echo "Commit message does not have the required format: "
   exit 1
-fi 
+fi
 
 exit 0
